version: '3.8'
services:
  otel-collector:
    environment:
      - LOG_LEVEL=debug
    ports:
      - "55680:55680" # OTLP HTTP (optional)
  jaeger:
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    ports:
      - "9411:9411" # Zipkin endpoint (optional)
