version: '3.8'
services:
  otel-collector:
    image: otel/opentelemetry-collector:latest
    command: ["--config=/etc/otelcol/config.yaml"]
    volumes:
      - ./collector.yaml:/etc/otelcol/config.yaml:ro
    ports:
      - "4317:4317" # OTLP gRPC
    depends_on:
      - jaeger

  jaeger:
    image: jaegertracing/all-in-one:1.41
    ports:
      - "16686:16686" # UI
      - "6831:6831/udp"
